### PR TITLE
You need to hook into both luastates at once.

### PR DESCRIPTION
**Pull request by Iamgoofball**
The VR lua layer is a different lua layer than the flatscreen layer. I noticed your code will check which layer it starts with/finds first and initalizes based on that.

The game defaults to the non-VR mode then turns on the VR mode, so you'll need to hook into both states at the start.

I'd file this as an issue but I can't because no issues enabled on the repo.

### CODE REVIEW

**Comment by ZNixian** [comment]
When I was testing, when run in VR only the VR-specific luaL_newstate was called - unless they've changed something, I'm a bit confused about this.

Do you mean the Lua was run twice, once for flat and once for VR?

Oh, and I'll turn on comments. I think they were disabled because this is a fork.

**Comment by Iamgoofball** [comment]
We noticed that hook overriding lua only works on the flat, and isn't being reflected in the vr side, with stuff like weapon lock disables working in the flat but shutting off in the vr mode.

**Comment by ZNixian** [comment]
Huh, that's odd. Do you want me to make you a special version that displays a popup when one of the hooks is run?

**Comment by Iamgoofball** [comment]
fixed in latest iirc

**Comment by ZNixian** [comment]
See 56ec03c

**Pull request closed without merging**
